---
- name: Generate templates and create new repo
  hosts: infra1
  gather_facts: false
  # connection: local
  vars:
    dst_template_path: /tmp/__tmp4repo
    token: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              39343030323630303135663639316430376262623839633761646130306164326234366233383762
              6364626665396364363964363434366431313066343762620a303765393862636437653134313162
              31666662373139356339613932623139373933373633336365306431623933323538363832643139
              6166383061313036640a356264366238653433366137326639313938626637663961386661396664
              36386138643665306161613738646137343539313830363432336261363765313739386231303465
              6231633738336239393134636564396236663537646662316466
    acm_git: https://github.com/mancubus77/e2e-root-acm-repo.git
    giturl: "https://{{token}}@"
    # cluster_name: glebe
    # cluster_location: glebe-2077-nsw
    machine_network: 10.1.196.0/24
  tasks: 

    - name: Ensure directoy is empty
      ansible.builtin.file:
        path: "{{ dst_template_path }}"
        state: absent
      ignore_errors: true

    - name: Create new folder
      ansible.builtin.file:
        path: "{{ dst_template_path }}"
        state: directory

    - name: Generate templates
      vars:
        # ansible_connection: local
        # cluster_name: hornsby
        # cluster_location: hornsby-2077-nsw
        # machine_network: 10.1.196.0/24
      include_role:
        name: e2e-add-cluster-playbooks
        # apply:
        #   delegate_to: infra1

    - name: Delete Github repository
      vars:
        connection: ssh
        ansible_python_interpreter: /usr/bin/python2
      community.general.github_repo:
        # username: mancubus77@gmail.com
        access_token: "{{ token }}"
        name: "e2e-{{ cluster_name }}-cluster"
        description: "Just for fun"
        private: no
        state: absent
        # force_defaults: no
      register: _result
      # delegate_to: infra1
    
    - name: Create Github repository
      vars:
        connection: ssh
        ansible_python_interpreter: /usr/bin/python2
      community.general.github_repo:
        access_token: "{{ token }}"
        name: "e2e-{{ cluster_name }}-cluster"
        description: "Just for fun"
        private: no
        state: present
        # force_defaults: no
      register: _result
      # delegate_to: infra1

    - name: Add Files to GIT
      shell: "{{ item }}"
      args:
        chdir: "{{ dst_template_path }}"
      with_items: 
        - git init
        - git add * 
        - git config user.name "ZTP ROBO"
        - git config user.email ztp@ztp.com
        - git commit -m "first commit"
        - git branch -M main
        - git remote add origin {{ _result.repo.clone_url | regex_replace('(https:\/\/)', giturl) }}
        - git push -u origin main 

    - name: Generate ACM APP 
      vars:
        # - cluster_name: hornsby
        - dst_template_path: /tmp/lol1
        - git_url: "{{ _result.repo.clone_url }}"
      include_role:
        name: e2e-ansible-acm-app-template

    - name: Ensure directoy is empty
      ansible.builtin.file:
        path: "/tmp/acm-repo"
        state: absent
      ignore_errors: true

    - name: Create folder
      ansible.builtin.file:
        path: "/tmp/acm-repo"
        state: directory

    - name: Checkout repo
      shell: "{{ item }}"
      args:
        chdir: "/tmp/acm-repo"
      with_items:
        - git clone "{{ acm_git | regex_replace('(https:\/\/)', giturl) }}" .
        - git config user.name "ZTP ROBO"
        - git config user.email ztp@ztp.com
        - mkdir managed-subscriptions/apps/vran-{{ cluster_name }}
        - cp /tmp/lol1/* managed-subscriptions/apps/vran-{{ cluster_name }}/
        - git add managed-subscriptions/apps/vran-{{ cluster_name }}/*
        - git config user.name "ZTP ANSIBLE ROBO"
        - git config user.email ztp@redhat.com
        - git commit -a -m "Ansible| adding new cluster {{ cluster_name }}"
        - git push 

    - name: Ensure directoy is empty
      ansible.builtin.file:
        path: "/tmp/acm-repo"
        state: absent
      ignore_errors: true
